/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package camping.main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author tobis
 */
public class Main extends javax.swing.JFrame {
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kodeAlat = new javax.swing.JLabel();
        namaAlat = new javax.swing.JLabel();
        merkAlat = new javax.swing.JLabel();
        kondisiAlat = new javax.swing.JLabel();
        kelengkapanAlat = new javax.swing.JLabel();
        hargaSewaAlat = new javax.swing.JLabel();
        stokAlat = new javax.swing.JLabel();
        titlePanel = new javax.swing.JLabel();
        inputNamaAlat = new javax.swing.JTextField();
        inputKodeAlat = new javax.swing.JTextField();
        inputKondisiAlat = new javax.swing.JTextField();
        inputMerkAlat = new javax.swing.JTextField();
        inputKelengkapanAlat = new javax.swing.JTextField();
        inputHargaSewaAlat = new javax.swing.JTextField();
        inputStokAlat = new javax.swing.JTextField();
        navigasiPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlatCamping = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        kodeAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kodeAlat.setText("Kode Alat");

        namaAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaAlat.setText("Nama Alat");

        merkAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        merkAlat.setText("Merk");

        kondisiAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kondisiAlat.setText("Kondisi");

        kelengkapanAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelengkapanAlat.setText("Kelengkapan");

        hargaSewaAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hargaSewaAlat.setText("Harga Sewa");

        stokAlat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stokAlat.setText("Stok");

        titlePanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePanel.setText("Penyewaan Alat Camping");

        inputNamaAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaAlatActionPerformed(evt);
            }
        });

        inputKodeAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKodeAlatActionPerformed(evt);
            }
        });

        inputKondisiAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKondisiAlatActionPerformed(evt);
            }
        });

        inputMerkAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMerkAlatActionPerformed(evt);
            }
        });

        inputKelengkapanAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKelengkapanAlatActionPerformed(evt);
            }
        });

        inputHargaSewaAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaSewaAlatActionPerformed(evt);
            }
        });

        inputStokAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStokAlatActionPerformed(evt);
            }
        });

        navigasiPanel.setBackground(new java.awt.Color(102, 153, 255));
        navigasiPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("1. Tekan Tombol \"Save\" Untuk Menyimpan Data Alat Camping");

        jLabel2.setText("2. Tekan Tombol \"Edit\" Untuk Edit Data Alat Camping");

        jLabel3.setText("3. Tekan Tombol \"Delete\" Untuk Menghapus Data Alat Camping");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Navigasi");

        javax.swing.GroupLayout navigasiPanelLayout = new javax.swing.GroupLayout(navigasiPanel);
        navigasiPanel.setLayout(navigasiPanelLayout);
        navigasiPanelLayout.setHorizontalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(navigasiPanelLayout.createSequentialGroup()
                        .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        navigasiPanelLayout.setVerticalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(35, 35, 35))
        );

        editButton.setBackground(new java.awt.Color(102, 153, 255));
        editButton.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        editButton.setText("Edit");
        editButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(102, 153, 255));
        saveButton.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(102, 153, 255));
        deleteButton.setFont(new java.awt.Font("Ubuntu Mono", 1, 12)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        tableAlatCamping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Merk", "Kondisi", "Kelengkapan", "Harga Sewa", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tableAlatCamping);

        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tobi Saputra");

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("202243502612");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaAlat)
                            .addComponent(kodeAlat)
                            .addComponent(merkAlat)
                            .addComponent(kondisiAlat)
                            .addComponent(kelengkapanAlat)
                            .addComponent(hargaSewaAlat)
                            .addComponent(stokAlat))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputStokAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHargaSewaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputKelengkapanAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputKondisiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputKodeAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMerkAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(navigasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodeAlat)
                            .addComponent(inputKodeAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaAlat)
                            .addComponent(inputNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(merkAlat)
                            .addComponent(inputMerkAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kondisiAlat)
                            .addComponent(inputKondisiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelengkapanAlat)
                            .addComponent(inputKelengkapanAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaSewaAlat)
                            .addComponent(inputHargaSewaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokAlat)
                            .addComponent(inputStokAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(navigasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaAlatActionPerformed

    private void inputKodeAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKodeAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKodeAlatActionPerformed

    private void inputKondisiAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKondisiAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKondisiAlatActionPerformed

    private void inputMerkAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMerkAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMerkAlatActionPerformed

    private void inputKelengkapanAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKelengkapanAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKelengkapanAlatActionPerformed

    private void inputHargaSewaAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaSewaAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaSewaAlatActionPerformed

    private void inputStokAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStokAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStokAlatActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (inputKodeAlat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Mengubah Data Kamu Belum Mengisi Kode Alat!");
        }
        String sql = "SELECT * FROM alat_camping WHERE kode_alat=?";
        try (Connection conn = getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, inputKodeAlat.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                sql =  "UPDATE alat_camping SET nama_alat=?, merk=?, kondisi=?, kelengkapan=?, harga_sewa=?, stok=? WHERE kode_alat=?";
                PreparedStatement updatePs = conn.prepareStatement(sql);
                updatePs.setString(1, inputNamaAlat.getText().isEmpty() ? rs.getString("nama_alat") : inputNamaAlat.getText());
                updatePs.setString(2, inputMerkAlat.getText().isEmpty() ? rs.getString("merk") : inputMerkAlat.getText());
                updatePs.setString(3, inputKondisiAlat.getText().isEmpty() ? rs.getString("kondisi") : inputKondisiAlat.getText());
                updatePs.setString(4, inputKelengkapanAlat.getText().isEmpty() ? rs.getString("kelengkapan") : inputKelengkapanAlat.getText());
                updatePs.setString(5, inputHargaSewaAlat.getText().isEmpty() ? rs.getString("harga_sewa") : inputHargaSewaAlat.getText());
                updatePs.setString(6, inputStokAlat.getText().isEmpty() ? rs.getString("stok") : inputStokAlat.getText());
                updatePs.setString(7, inputKodeAlat.getText().toUpperCase()); // Primary Key
                updatePs.executeUpdate();
                loadDataTable();
                clearAllInput();
                JOptionPane.showMessageDialog(null, "Data Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Berhasil Di Update!");
            } else {
                JOptionPane.showMessageDialog(null, "Data Alat Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Tidak Terdaftar!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan Saat Pencarian Database :\n" + e.getMessage());
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (inputKodeAlat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Menyimpan Data Kamu Belum Mengisi Kode Alat!");
        }
        String sql = "SELECT * FROM alat_camping WHERE kode_alat=?";
        try (Connection conn = getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, inputKodeAlat.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Data Alat Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Sudah Terdaftar!");
            } else {
                sql = "INSERT INTO alat_camping (kode_alat, nama_alat, merk, kondisi, kelengkapan, harga_sewa, stok) VALUES " +
                        "(?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement insertPs = conn.prepareStatement(sql);
                insertPs.setString(1, inputKodeAlat.getText().toUpperCase()); // Primary Key
                insertPs.setString(2, inputNamaAlat.getText());
                insertPs.setString(3, inputMerkAlat.getText());
                insertPs.setString(4, inputKondisiAlat.getText());
                insertPs.setString(5, inputKelengkapanAlat.getText());
                insertPs.setString(6, inputHargaSewaAlat.getText());
                insertPs.setString(7, inputStokAlat.getText());
                insertPs.executeUpdate();
                loadDataTable();
                clearAllInput();
                JOptionPane.showMessageDialog(null, "Data Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Berhasil Di Simpan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan Saat Pencarian Database :\n" + e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (inputKodeAlat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Menghapus Data Kamu Belum Mengisi Kode Alat!");
        }
        String sql = "SELECT * FROM alat_camping WHERE kode_alat=?";
        try (Connection conn = getConnection();
            PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, inputKodeAlat.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                sql =  "DELETE FROM alat_camping WHERE kode_alat=?";
                PreparedStatement deletePs = conn.prepareStatement(sql);
                deletePs.setString(1, inputKodeAlat.getText().toUpperCase()); // Primary Key
                deletePs.executeUpdate();
                loadDataTable();
                clearAllInput();
                JOptionPane.showMessageDialog(null, "Data Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Berhasil Di Hapus!");
            } else {
                JOptionPane.showMessageDialog(null, "Data Alat Dengan Kode : " + inputKodeAlat.getText().toUpperCase() + " Tidak Terdaftar!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kesalahan Saat Pencarian Database :\n" + e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private static Connection getConnection() {
        String URL = "jdbc:mysql://localhost:3306/camping";
        String USER = "root";
        String PASSWORD = "";
        try {
            if (connection == null || connection.isClosed()) {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(URL, USER, PASSWORD);
                System.out.println("Berhasil Connect ke Database!");
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println("Database connection error: " + e.getMessage());
        }
        return connection;
    }
    
    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) tableAlatCamping.getModel();
        model.setRowCount(0); 

        String sql = "SELECT * FROM alat_camping";
        try (Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Object[] row = new Object[]{
                    rs.getString("kode_alat"),
                    rs.getString("nama_alat"),
                    rs.getString("merk"),
                    rs.getString("kondisi"),
                    rs.getString("kelengkapan"),
                    rs.getString("harga_sewa"),
                    rs.getString("stok")
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data tabel: " + e.getMessage());
        }
    }

    /**
     * Clear Semua Input
     * Optimalisasi Performa by Tobz
     */
    private void clearAllInput() {
        inputKodeAlat.setText("");
        inputNamaAlat.setText("");
        inputMerkAlat.setText("");
        inputKondisiAlat.setText("");
        inputKelengkapanAlat.setText("");
        inputHargaSewaAlat.setText("");
        inputStokAlat.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main main = new Main();
                main.setVisible(true);
                main.loadDataTable();
            }
        });
    }
    
    private static Connection connection;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel hargaSewaAlat;
    private javax.swing.JTextField inputHargaSewaAlat;
    private javax.swing.JTextField inputKelengkapanAlat;
    private javax.swing.JTextField inputKodeAlat;
    private javax.swing.JTextField inputKondisiAlat;
    private javax.swing.JTextField inputMerkAlat;
    private javax.swing.JTextField inputNamaAlat;
    private javax.swing.JTextField inputStokAlat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelengkapanAlat;
    private javax.swing.JLabel kodeAlat;
    private javax.swing.JLabel kondisiAlat;
    private javax.swing.JLabel merkAlat;
    private javax.swing.JLabel namaAlat;
    private javax.swing.JPanel navigasiPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel stokAlat;
    private javax.swing.JTable tableAlatCamping;
    private javax.swing.JLabel titlePanel;
    // End of variables declaration//GEN-END:variables
}
